version: '3'
services:
  spillman-api-img:
    build:
      context: .
      dockerfile: Dockerfile
    image: sccity/spillman-api:img
    container_name: spillman-api-img
    ports:
      - "8080:5000"
    volumes:
      - "$PWD/config:/app/config:ro"
    restart: unless-stopped